### ISSUE TITLE
I think in ln[12] 'Remove columns with more than 40% missing data'

### ISSUE THREAD

**Issue by SeongJinAhn** [dimitreOliveira/MachineLearning#1]
should be changed as 'Remove columns with more than 60% missing data'

because  'train[c].count() = len(train) - number of Null ' 

isn't it right?

**Comment by dimitreOliveira** [comment]
Hi SeongJinAhn,
Thanks for the heads up, but about what file are you talking about?

**Comment by SeongJinAhn** [comment]
Oh I was talking about MS Malware Prediction, EDA and LGBM file
https://github.com/dimitreOliveira/MachineLearning/blob/master/Kaggle/Microsoft%20Malware%20Prediction/Malware%20Detection%20-%20EDA%20and%20LGBM.ipynb

**Comment by dimitreOliveira** [comment]
I fixed it, thanks SeongJinAhn!
